FileVersion = 1
Projects = {meteorite = {Path = "."}, GLFW = "*", ImGui = "*", ImGuiImplGlfw = "*", MiniZ = "*", stb_beef = "*", Wgpu = "*", Wgpu-Imgui = "*", Wgpu-Glfw = "*"}

[Workspace]
StartupProject = "meteorite"

[Configs.Debug.Win64]
AllocStackTraceDepth = 10

[Configs.Release.Win64]
AllocType = "Custom"
AllocMalloc = "je_malloc"
AllocFree = "je_free"
