FileVersion = 1
Dependencies = {corlib = "*", GLFW = "*", ImGui = "*", ImGuiImplGlfw = "*", MiniZ = "*", Wgpu = "*", Wgpu-Glfw = "*", Wgpu-Imgui = "*", stb_beef = "*"}

[Project]
Name = "meteorite"
StartupObject = "Meteorite.Program"
DefaultNamespace = "Meteorite"
