FileVersion = 1
Projects = {meteorite = {Path = "."}, GLFW = "*", ImGui = "*", ImGuiImplGlfw = "*", MiniZ = "*", stb_beef = "*", Wgpu = "*", Wgpu-Imgui = {Path = "../../../../../Program Files/BeefLang/BeefLibs/Wgpu/wgpu-imgui"}, Wgpu-Glfw = {Path = "../../../../../Program Files/BeefLang/BeefLibs/Wgpu/wgpu-glfw"}}

[Workspace]
StartupProject = "meteorite"

[Configs.Debug.Win64]
AllocStackTraceDepth = 10

[Configs.Release.Win64]
AllocType = "Custom"
AllocMalloc = "je_malloc"
AllocFree = "je_free"
