FileVersion = 1
Dependencies = {corlib = "*", GLFW = "*", ImGui = "*", ImGuiImplGlfw = "*", MiniZ = "*", stb_beef = "*", Bulkan = "*", "Bulkan.Utilities" = "*", Cacti = "*"}

[Project]
Name = "Meteorite"
StartupObject = "Meteorite.Program"
