FileVersion = 1
Projects = {Meteorite = {Path = "."}, GLFW = "*", ImGui = "*", MiniZ = "*", stb_beef = "*", Cacti = {Path = "cacti"}}
Unlocked = ["Shaderc"]

[Workspace]
StartupProject = "Meteorite"

[Configs.Release.Win64]
AllocType = "JEMalloc"

[Configs.Debug.Win64]
AllocStackTraceDepth = 10
