FileVersion = 1
Projects = {meteorite = {Path = "."}, GLFW = "*", ImGui = "*", ImGuiImplGlfw = "*", MiniZ = "*", stb_beef = "*", Wgpu = "*", Wgpu-Glfw = "*", Wgpu-Imgui = "*"}

[Workspace]
StartupProject = "meteorite"

[Configs.Release.Win64]
AllocType = "JEMalloc"

[Configs.Debug.Win64]
AllocStackTraceDepth = 5
