FileVersion = 1
Dependencies = {corlib = "*", GLFW = "*", ImGui = "*", ImGuiImplGlfw = "*", MiniZ = "*", stb_beef = "*", Wgpu = "*", Wgpu-Glfw = "*", Wgpu-Imgui = "*"}

[Project]
Name = "meteorite"
StartupObject = "Meteorite.Program"
DefaultNamespace = "Meteorite"

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)/dist/windows/jemallocso.lib"]
PostBuildCmds = ["CopyFilesIfNewer(\"$(ProjectDir)/dist/windows/*.dll\", \"$(BuildDir)\")"]
