FileVersion = 1
Dependencies = {corlib = "*", Bulkan = "*", "Bulkan.Utilities" = "*", GLFW = "*", Shaderc = "*", stb_beef = "*", ImGui = "*", MiniZ = "*"}

[Project]
Name = "Cacti"
TargetType = "BeefLib"
StartupObject = "Cacti.Program"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)/wolfssl_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)/wolfssl.lib"]

[Configs.Paranoid.Win64]
LibPaths = ["$(ProjectDir)/wolfssl.lib"]

[Configs.Test.Win64]
LibPaths = ["$(ProjectDir)/wolfssl.lib"]
