FileVersion = 1
Dependencies = {corlib = "*", Bulkan = "*", "Bulkan.Utilities" = "*", GLFW = "*", Shaderc = "*", stb_beef = "*", ImGui = "*", MiniZ = "*"}

[Project]
Name = "Cacti"
TargetType = "BeefLib"
StartupObject = "Cacti.Program"
