name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Beef
        run: |
          Start-BitsTransfer -Source "https://nightly.beeflang.org/BeefSetup.exe" -Destination "BeefBuild.exe"
          7z x BeefBuild.exe -oBeef
      
      - name: Configure Beef
        run: |
          "Version = 1`nUnversionedLibDirs = [`"Beef/BeefLibs`"]" | Out-File -FilePath "BeefConfig.toml"
      
      - name: Download GLFW
        run: git clone https://github.com/MineGame159/glfw-beef.git Beef/BeefLibs/glfw-beef
      
      - name: Download ImGui
        run: git clone https://github.com/RogueMacro/imgui-beef.git Beef/BeefLibs/imgui-beef
      
      - name: Download Bulkan
        run: git clone https://github.com/jayrulez/Bulkan.git Beef/BeefLibs/Bulkan
      
      - name: Download Shaderc
        run: git clone https://github.com/MineGame159/shaderc-beef.git Beef/BeefLibs/shaderc-beef
      
      - name: Download Stb
        run: git clone https://github.com/EinScott/stb_beef.git Beef/BeefLibs/stb_beef
      
      - name: Build
        run: Beef/bin/BeefBuild.exe -config=Release
      
      - name: Download assets
        run: |
          Start-BitsTransfer -Source "https://piston-data.mojang.com/v1/objects/977727ec9ab8b4631e5c12839f064092f17663f8/client.jar" -Destination "minecraft.jar"
          7z x minecraft.jar assets/minecraft
      
      - name: Create ZIP archive
        run: |
          Copy-Item -Path build/Release_Win64/meteorite/meteorite.exe -Destination .
          Copy-Item -Path build/Release_Win64/meteorite/*.dll -Destination .
          7z a -tzip meteorite.zip assets meteorite.exe *.dll
          
      - name: Upload meteorite as artifact
        uses: actions/upload-artifact@v3
        if: github.ref != format('refs/heads/{0}', github.event.repository.default_branch) # Only runs if this CI was not triggered by the default branch
        with:
          name: meteorite
          path: meteorite.zip
      
      - name: Update release
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)  # Only runs if this CI was triggered by the default branch
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: Meteorite
          files: meteorite.zip
